server:
  port: 80
  error:
    path: /error
spring:
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: '0928'
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      max-lifetime: 1800000
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      connection-timeout: 30000
      connection-test-query: select 1 from dual
    url: jdbc:mysql://104.199.242.28:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: production
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.webapp.entity